# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3124c79d1d5995faa25679dfa279314afae6d12aeb29cbdcaefeca5249d7e66217eea6036db90ca02d6d831b6d2f7ab9ff84e4f03646e19d207eedf0b3aca064

test:
  secret_key_base: a56f7d16f0d8c7506d2c99c0b7681c538d6ab7e85481a1fbfca781535664dac0cca43a7c5ba62adb90ff1e3e9b91a14a635845661468694c609101a8c3251c15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
